max_num_threads:  1 
save_trajectory: true
suspend_on_failure: false
output_dir: .outputs
max_frames: -1 # For negative values, all frames are computed
display_debug: true

# DATASET OPTIONS ----
dataset_options:
  dataset: KITTI_raw # Options: [KITTI_raw / KITTI_CARLA / KITTI]
  root_path: ../.kitti_raw # Set to the root path of kitti's directory
  fail_if_incomplete: false
  min_dist_lidar_center: 3.0 # Suppresses points to close to the center of the sensor
  max_dist_lidar_center: 100.0 # Suppresses points to far from the center of the sensor

# ODOMETRY OPTIONS ----
odometry_options:
  voxel_size: 0.5 # The voxel size for the grid sampling of the new frame (before keypoints extraction)
  sample_voxel_size: 1.5 # The size of a voxel for the selection of `keypoints` by grid sampling
  max_distance: 100.0 # The threshold of the distance to suppress voxels from the map
  max_num_points_in_voxel: 20 # The maximum number of points per voxel of the map
  debug_print: true
  min_distance_points: 0.1
  distance_error_threshold: 5.0 # The motion of the sensor between two frames which is considered erroneous (stops the odometry)
  motion_compensation: CONTINUOUS # The profile of the motion compensation (NONE, CONSTANT_VELOCITY, ITERATIVE, CONTINUOUS)

  # CT_ICP OPTIONS ----
  ct_icp_options:
    size_voxel_map: 1.5 # The voxel size of in the voxel map
    num_iters_icp: 5 # The number of iterations of the ICP
    min_number_neighbors: 20 # The minimum number of neighbor points to define a valid neighborhood
    voxel_neighborhood: 1
    max_number_neighbors: 20
    max_dist_to_plane_ct_icp: 0.3
    norm_x_end_iteration_ct_icp: 0.001
    debug_print: false
    point_to_plane_with_distortion: true
    distance: CT_POINT_TO_PLANE # Options: [CT_POINT_TO_PLANE, POINT_TO_PLANE]
    num_closest_neighbors: 1
    beta_location_consistency: 0.001
    beta_constant_velocity: 0.001

    solver: GN # Options: [GN=Gauss-Newton, CERES]
    loss_function: HUBER # Options: [STANDARD, CAUCHY, HUBER, TOLERANT, TRUNCATED] (for CERES solver)
    ls_max_num_iters: 1 # The number of steps performed for each iteration of the ICP (for CERES solver)
    ls_num_threads:  16 # The number of threads to build and solve the least square system (for CERES solver)
    ls_sigma: 0.1 # The sigma parameter for loss CAUCHY, HUBER, TOLERANT, TRUNCATED (for CERES solver)
    ls_tolerant_min_threshold: 0.05 # The tolerant parameter for loss TOLERANT (for CERES solver)

