max_num_threads: 1
save_trajectory: true
suspend_on_failure: false
output_dir: .outputs_nclt_DEBUG_1
all_sequences: false
sequence: "2012-04-29_vel" # Ignored if use_all_sequences is true
start_index: 17800 # The initial frame index for the given sequence
max_frames: -1 # For negative values, all frames are computed
display_debug: true

# DATASET OPTIONS ----
dataset_options:
  dataset: NCLT # Options: [KITTI_raw / KITTI_CARLA / NCLT]
  root_path: ../.nclt # Set to the root path of kitti's directory
  fail_if_incomplete: false
  min_dist_lidar_center: 0.5 # Suppress points too close to the center of the sensor
  max_dist_lidar_center: 100.0 # Suppress points to far from the center of the sensor
  nclt_num_aggregated_pc: 220 #

# ODOMETRY OPTIONS ----
odometry_options:
  voxel_size: 0.5 # The voxel size for the grid sampling of the new frame (before keypoints extraction)
  sample_voxel_size: 0.8 # The size of a voxel for the selection of `keypoints` by grid sampling
  max_distance: 100.0 # The threshold of the distance to suppress voxels from the map
  max_num_points_in_voxel: 20 # The maximum number of points per voxel of the map
  debug_print: true
  min_distance_points: 0.20
  distance_error_threshold: 100.0 # The motion of the sensor between two frames which is considered erroneous (stops the odometry)
  motion_compensation: CONTINUOUS  # The profile of the motion compensation (NONE, CONSTANT_VELOCITY, ITERATIVE, CONTINUOUS)
  initialization: INIT_NONE

  # CT_ICP OPTIONS ----
  ct_icp_options:
    size_voxel_map: 1.0 # The voxel size of in the voxel map
    num_iters_icp: 50 # The number of iterations of the ICP
    min_number_neighbors: 20 # The minimum number of neighbor points to define a valid neighborhood
    voxel_neighborhood: 1
    max_number_neighbors: 20
    max_dist_to_plane_icp: 0.8
    norm_x_end_iteration_ct_icp: 0.001
    debug_print: false
    point_to_plane_with_distortion: true
    distance: CT_POINT_TO_PLANE # Options: [CT_POINT_TO_PLANE, POINT_TO_PLANE]
    num_closest_neighbors: 1
    alpha_location_consistency: 0.0001
    alpha_constant_velocity: 0.0

    loss_function: CAUCHY # Options: [CAUCHY, STANDARD, HUBER, TOLERANT, TRUNCATED]
    ls_max_num_iters: 50 # The number of steps performed by ceres for each iteration of the ICP
    ls_num_threads: 8 # The number of threads to build and solve the least square system
    ls_sigma: 0.1
    ls_tolerant_min_threshold: 0.05

