sample_frequency: 20.0 # The frequency of frame acquisition
max_lidar_distance: 15.0
num_points_per_primitives: 300

acquisition:
  # Ground truth Poses
  poses:
    - quaternion: [ 0, 0, 0, 1 ]
      translation: [ 2.5, 5, 2 ]
      dest_frame_id: 0
    - quaternion: [ 0.4, 0.5, 0.3, 1 ]
      translation: [ 7.5, 5, 2 ]
      dest_frame_id: 1
    - quaternion: [ 0.2, 0.7, 0.1, 1 ]
      translation: [ 7.5, 15, 3 ]
      dest_frame_id: 2
    - quaternion: [ 0.02, 0.3, 0.1, 1 ]
      translation: [ 7.5, 25, 2 ]
      dest_frame_id: 3
    - quaternion: [ -0.1, 0.4, 0.2, 1 ]
      translation: [ 2.5, 25, 2 ]
      dest_frame_id: 4
    - quaternion: [ -0.3, 0.06, 0.07, 1 ]
      translation: [ 2.5, 35, 1 ]
      dest_frame_id: 5
    - quaternion: [ 0.01, 0.02, 0.6, 1 ]
      translation: [ 7.5, 35, 1.5 ]
      dest_frame_id: 6
    - quaternion: [ 0.01, -0.07, 0.01, 1 ]
      translation: [ 12.5, 35, 2 ]
      dest_frame_id: 7
    - quaternion: [ 0, 0, 0.001, 1 ]
      translation: [ 12.5, 25, 2.5 ]
      dest_frame_id: 8
    - quaternion: [ -0.1, 0.8, 0.9, 0.1 ]
      translation: [ 12.5, 15, 2 ]
      dest_frame_id: 9
    - quaternion: [ 0, 0.2, 0.1, 1 ]
      translation: [ 12.5, 5, 3 ]
      dest_frame_id: 10

  triangles:
    # GROUND
    - [ [ 0, 0, 0 ], [ 0, 10, 0 ], [ 5, 10, 0 ] ]
    - [ [ 0, 0, 0 ], [ 5, 0, 0 ], [ 5, 10, 0 ] ]

    - [ [ 5, 0, 0 ], [ 5, 10, 0 ], [ 10, 10, 0 ] ]
    - [ [ 5, 0, 0 ], [ 10, 0, 0 ], [ 10, 10, 0 ] ]
    - [ [ 5, 10, 0 ], [ 5, 20, 0 ], [ 10, 20, 0 ] ]
    - [ [ 5, 10, 0 ], [ 10, 10, 0 ], [ 10, 20, 0 ] ]

    - [ [ 10, 0, 0 ], [ 10, 10, 0 ], [ 15, 10, 0 ] ]
    - [ [ 10, 0, 0 ], [ 15, 0, 0 ], [ 15, 10, 0 ] ]
    - [ [ 10, 10, 0 ], [ 10, 20, 0 ], [ 15, 20, 0 ] ]
    - [ [ 10, 10, 0 ], [ 15, 10, 0 ], [ 15, 20, 0 ] ]

    - [ [ 15, 0, 0 ], [ 15, 10, 0 ], [ 20, 10, 0 ] ]
    - [ [ 15, 0, 0 ], [ 20, 0, 0 ], [ 20, 10, 0 ] ]
    - [ [ 15, 10, 0 ], [ 15, 20, 0 ], [ 20, 20, 0 ] ]
    - [ [ 15, 10, 0 ], [ 20, 10, 0 ], [ 20, 20, 0 ] ]

    - [ [ 0, 20, 0 ], [ 0, 30, 0 ], [ 5, 30, 0 ] ]
    - [ [ 0, 20, 0 ], [ 5, 20, 0 ], [ 5, 30, 0 ] ]

    - [ [ 5, 20, 0 ], [ 5, 30, 0 ], [ 10, 30, 0 ] ]
    - [ [ 5, 20, 0 ], [ 10, 20, 0 ], [ 10, 30, 0 ] ]

    - [ [ 10, 20, 0 ], [ 10, 30, 0 ], [ 15, 30, 0 ] ]
    - [ [ 10, 20, 0 ], [ 15, 20, 0 ], [ 15, 30, 0 ] ]

    - [ [ 15, 20, 0 ], [ 15, 30, 0 ], [ 20, 30, 0 ] ]
    - [ [ 15, 20, 0 ], [ 20, 20, 0 ], [ 20, 30, 0 ] ]

    - [ [ 0, 30, 0 ], [ 0, 40, 0 ], [ 5, 40, 0 ] ]
    - [ [ 0, 30, 0 ], [ 5, 30, 0 ], [ 5, 40, 0 ] ]

    - [ [ 5, 30, 0 ], [ 5, 40, 0 ], [ 10, 40, 0 ] ]
    - [ [ 5, 30, 0 ], [ 10, 30, 0 ], [ 10, 40, 0 ] ]

    - [ [ 10, 30, 0 ], [ 10, 40, 0 ], [ 15, 40, 0 ] ]
    - [ [ 10, 30, 0 ], [ 15, 30, 0 ], [ 15, 40, 0 ] ]

    - [ [ 15, 30, 0 ], [ 15, 40, 0 ], [ 20, 40, 0 ] ]
    - [ [ 15, 30, 0 ], [ 20, 30, 0 ], [ 20, 40, 0 ] ]

    # WALLS
    - [ [ 0, 10, 0 ], [ 5, 10, 0 ], [ 5, 10, 5 ] ]
    - [ [ 0, 10, 0 ], [ 0, 10, 5 ], [ 5, 10, 5 ] ]
    - [ [ 0, 20, 0 ], [ 5, 20, 0 ], [ 5, 20, 5 ] ]
    - [ [ 0, 20, 0 ], [ 0, 20, 5 ], [ 5, 20, 5 ] ]

    - [ [ 5, 10, 0 ], [ 5, 10, 5 ], [ 5, 20, 0 ], ]
    - [ [ 5, 10, 5 ], [ 5, 20, 5 ], [ 5, 20, 0 ] ]

    - [ [ 0, 30, 0 ], [ 0, 40, 0 ], [ 0, 40, 5 ] ]
    - [ [ 0, 30, 0 ], [ 0, 30, 5 ], [ 0, 40, 5 ] ]

    - [ [ 0, 40, 0 ], [ 5, 40, 0 ], [ 5, 40, 5 ] ]
    - [ [ 0, 40, 0 ], [ 0, 40, 5 ], [ 5, 40, 5 ] ]

  lines:
    - [ [ 5, 0, 0 ], [ 5, 0, 5 ] ]
    - [ [ 10, 0, 0 ], [ 10, 0, 5 ] ]
    - [ [ 10, 10, 0 ], [ 10, 10, 5 ] ]
    - [ [ 10, 20, 0 ], [ 10, 20, 5 ] ]
    - [ [ 10, 30, 0 ], [ 10, 30, 5 ] ]

    - [ [ 15, 0, 0 ], [ 15, 0, 5 ] ]
    - [ [ 15, 10, 0 ], [ 15, 10, 5 ] ]
    - [ [ 15, 20, 0 ], [ 15, 20, 5 ] ]
    - [ [ 15, 30, 0 ], [ 15, 30, 5 ] ]

  spheres:
    - radius: 1.0
      center: [ 10, 0, 5 ]

    - radius: 0.5
      center: [ 10, 10, 5 ]

    - radius: 2.0
      center: [ 10, 20, 5 ]

    - radius: 0.2
      center: [ 10, 30, 5 ]